### ISSUE TITLE
Feature suggestions

### ISSUE THREAD

**Issue by ottsch** [toiq/obsidian-sidebar-expand-on-hover#1]
Nice one!

Two suggestions:

- Allow user to also select only one sidebar to expand on hover
- When clicking on the arrow (> <), sidebar should stay expanded IMO until clicked again

**Comment by toiq** [comment]
Hello @ottsch! Thanks for the feature suggestions. I've already addressed your first suggestion. As for the second one, I will need some time. I need to take a look into the API and clean my code first but I barely have any time for this project at the moment (Because of exam). But hopefully, I'll add the second feature very soon.

**Comment by toiq** [comment]
I actually thought about how to do this more "elegantly". 
You can now double click on ribbons to enable/disable the corresponding sidebars and when you do disable one sidebar by double clicking on the ribbon, it stays expanded.

**Comment by dxcore35** [comment]
Please let user chose just left or right or both sidebars to be automated via this plugin! 🧡

**Comment by toiq** [comment]
@dxcore35 , You can already do this by simply **double clicking** on the ribbon to toggle automate behavior (on and off) for that ribbon. If you still need a dedicated plugin setting then let me know. 😃

**Comment by dxcore35** [comment]
Amazing. The option will be great! As you see I need to ask here to know the functionality is already here. What about basic user who don't know what github is. 

Anyway thank you for the plugin!
_I was thinking about this function way back before the plugins were open... but it was not possible to do just with CSS._

**Comment by isle99** [comment]
What about giving us some hotkeys for enabling/disabling them as well?

**Comment by toiq** [comment]
<del>Hi @isle99! Please create a new issue. 😅</del>

Edit: Never mind. 
> Amazing. The option will be great! As you see I need to ask here to know the functionality is already here. What about basic user who don't know what github is.
> 
> Anyway thank you for the plugin!
> _I was thinking about this function way back before the plugins were open... but it was not possible to do just with CSS._

and 

> What about giving us some hotkeys for enabling/disabling them as well?

I've added plugin settings to enable/disable each sidebar individually and commands so that you may be able to set hotkeys for those. 😄
